#!/usr/bin/env php
<?php
// 定义项目路径
define('APP_PATH', __DIR__ . '/Application/');
define('ROOT_PATH', __DIR__);

// 加载框架引导文件
require __DIR__.'/vendor/hbynlsl/tiny-mvc/src/Console.php';

hbynlsl\Console::run();